const State = {
  data: [
    {
      name: 'VolksWagen Polo',
      rent: 17,
      classify: 'Эконом',
      transmission: 'Механика',
      fuel: 'Бензин',
      src: 'polo',
      power: '110 л.с',
      drive_unit: 'передний',
      engine_capacity: '1,4 л',
      acceleration: '11,7 с.',
      consumption: '5,8 л',
      trunk_volume: '5б9 л.',
      fuel_tank_volume: '55 л.',
      weight: '1208 кг',
      doors: 4,
      seats: 5,
      id: 1
    },
    {
      name: 'Toyota Corolla',
      rent: 22,
      classify: 'Средний',
      transmission: 'Автомат',
      fuel: 'Бензин',
      src: 'Corolla',
      power: '124 л.с',
      drive_unit: 'передний',
      engine_capacity: '1,6 л',
      acceleration: '12,1 с.',
      consumption: '7,2 л',
      trunk_volume: '450 л.',
      fuel_tank_volume: '55 л.',
      weight: '1320 кг',
      doors: 4,
      seats: 5,
      id: 2
    },
    {
      name: 'Honda Civic AT',
      rent: 24,
      classify: 'Средний',
      transmission: 'Автомат',
      fuel: 'Бензин',
      src: 'honda-civic-at',
      power: '142 л.с',
      drive_unit: 'передний',
      engine_capacity: '1,8 л',
      acceleration: '10,9 с.',
      consumption: '6,3 л',
      trunk_volume: '477 л.',
      fuel_tank_volume: '50 л.',
      weight: '1242 кг',
      doors: 4,
      seats: 5,
      id: 3
    },
    {
      name: 'Peugeot 301',
      rent: 25,
      classify: 'Средний',
      transmission: 'Автомат',
      fuel: 'Бензин',
      src: 'Peugeot-301',
      power: '82 л.с',
      drive_unit: 'передний',
      engine_capacity: '1,2 л',
      acceleration: '12,9 с.',
      consumption: '4,8 л',
      trunk_volume: '477 л.',
      fuel_tank_volume: '50 л.',
      weight: '980 кг',
      doors: 4,
      seats: 5,
      id: 4
    },
    {
      name: 'Kia Sportage',
      rent: 24,
      classify: 'Внедорожник',
      transmission: 'Автомат',
      fuel: 'Бензин',
      src: 'Sportage',
      power: '150 л.с',
      drive_unit: 'передний',
      engine_capacity: '2,0 л',
      acceleration: '11,1 с.',
      consumption: '7,9 л',
      trunk_volume: '491 л.',
      fuel_tank_volume: '62 л.',
      weight: '1501 кг',
      doors: 5,
      seats: 5,
      id: 5
    },
    {
      name: 'Chevrolet Camaro Convertible',
      rent: 120,
      classify: 'Бизнес',
      transmission: 'Автомат',
      fuel: 'Бензин',
      src: 'Camaro',
      power: '275 л.с',
      drive_unit: 'задний',
      engine_capacity: '2,0 л',
      acceleration: '5,5 с.',
      consumption: '9,4 л',
      trunk_volume: '262 л.',
      fuel_tank_volume: '72 л.',
      weight: '1636 кг',
      doors: 2,
      seats: 4,
      id: 6
    },
    {
      name: 'Mercedes GLE 250d 4MATIC',
      rent: 190,
      classify: 'Средний',
      transmission: 'Автомат',
      fuel: 'Бензин',
      src: 'MercedesBenz-GLE',
      power: '204 л.с',
      drive_unit: 'полный',
      engine_capacity: '2,1 л',
      acceleration: '8,6 с.',
      consumption: '9,4 л',
      trunk_volume: '260 л.',
      fuel_tank_volume: '72 л.',
      weight: '2950 кг',
      doors: 5,
      seats: 5,
      id: 7
    },
    {
      name: 'Mercedes Vito',
      rent: 37,
      classify: 'Минивен',
      transmission: 'Механика',
      fuel: 'Бензин',
      src: 'Mercedes Vito',
      power: '129 л.с',
      drive_unit: 'передний',
      engine_capacity: '2,0 л',
      acceleration: '10,2 с.',
      consumption: '7,5 л',
      trunk_volume: '1300 л.',
      fuel_tank_volume: '78 л.',
      weight: '2700 кг',
      doors: 4,
      seats: 6,
      id: 8
    }
  ],
  filter: '',
  checked: false,
  term: ''
};

export default State;
